name: bibaw_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.2.1
  uuid: ^2.0.4
  cloud_firestore: ^0.13.5
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  division: ^0.8.2
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  get_it: ^4.0.1
  grpc: ^2.1.3
  http: ^0.12.0+3
  meta: ^1.1.6
  protobuf: ^1.0.1
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.2.1+3
  lint: ^1.1.1
  mockito: ^4.1.1
  cloud_firestore_mocks: ^0.4.3+1

flutter:
  uses-material-design: true
